### ISSUE TITLE
"No results" when searching on first install

### ISSUE THREAD

**Issue by sametaor** [thatvegandev/gh-eco#4]
## Description

As soon as the extension is installed and the command to run is executed, it shows a "*> search by username*" prompt, with Enter and Esc as the only keybinds showing up. Entering a username results in a "No results" being displayed.
## To Reproduce

```
$ gh extension install jrnxf/gh-eco
$ gh eco
> *search by username*
> <any username>
```

## Expected behavior

The extension should display a simple array of commands as well as interactive navigation as shown in the gif.
## Screenshots

<img src="https://i.imgur.com/VYQCZdN.png"/>

## Environment

- OS: Windows 10 22H2
- Terminal Emulator: Windows Terminal/Windows Powershell
- Font: DejaVuSansM Nerd Font
- `gh-eco` version: v0.1.3

**Comment by BrunoBarlari** [comment]
Same problem on OSX 14.4

**Comment by bcook128** [comment]
Same problem on Linux (Ubuntu 22.04.04)

**Comment by jrnxf** [comment]
Sorry this took me so long! 😅 Life has been nuts lately but this is now fixed! Just run `gh extension upgrade eco` and you should be set!

**Comment by sametaor** [comment]
Woo, thanks a lot! Now I can finally enjoy the extension well again! Props for the response nonetheless! 🚀
